import { COLORS, icons, SIZES, images, FONTS } from '../../constants'

export const circleData = [
    {
        id: 1,
        title: 'Technology',
        iconName: icons.location,
        description: "Technology that evolves in the universe, didn't know what am typing. Lord I need your help.",
    }, {
        id: 2,
        title: 'Entertainment',
        iconName: icons.location,
        description: "Technology that evolves in the universe, didn't know what am typing. Lord I need your help.",
    }, {
        id: 3,
        title: 'Sport',
        iconName: icons.location,
        description: "Technology that evolves in the universe, didn't know what am typing. Lord I need your help.",
    }, {
        id: 4,
        title: 'LifeStyle',
        iconName: icons.location,
        description: "Technology that evolves in the universe, didn't know what am typing. Lord I need your help.",
    }, {
        id: 5,
        title: 'Religion',
        iconName: icons.location,
        description: "Technology that evolves in the universe, didn't know what am typing. Lord I need your help.",
    }, {
        id: 6,
        title: 'Books',
        iconName: icons.location,
        description: "Technology that evolves in the universe, didn't know what am typing. Lord I need your help.",
    },
];

export const hotFoodData = [
    {
        id: 1,
        title: 'Barbecue',
        foodImage: images.restaurant1,
        review: 'Highly recommended',
        reviewsNumber: 32,
    }, {
        id: 2,
        title: 'Beer Crayfish',
        foodImage: images.restaurant2,
        review: 'Highly recommended',
        reviewsNumber: 87,
    }, {
        id: 3,
        title: 'Spaghetti',
        foodImage: images.restaurant3,
        review: 'Highly recommended',
        reviewsNumber: 20,
    }, {
        id: 4,
        title: 'Pizza',
        foodImage: images.restaurant4,
        review: 'Highly recommended',
        reviewsNumber: 27,
    },
];

export const oldMarketData = [
    {
        id: 1,
        marketImage: images.image6,
        marketTitle: 'Mercy Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '80,000',
        status: 'Agent',
        // type: 'Hostel',
    }, {
        id: 2,
        marketImage: images.image6,
        marketTitle: 'New York Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '120,000',
        status: 'Owner',
    }, {
        id: 3,
        marketImage: images.image6,
        marketTitle: 'Goious Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '130,000',
        status: 'Agent',
    }, {
        id: 4,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Owner',
    }, {
        id: 5,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 6,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Owner',
    }, {
        id: 7,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 71,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 72,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 73,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 74,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 75,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 76,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 77,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 78,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 79,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 80,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 81,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 82,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 83,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 84,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 85,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 86,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 87,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 88,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 89,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 90,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 91,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 92,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 93,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 94,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 95,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 96,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 97,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 98,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 99,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    }, {
        id: 100,
        marketImage: images.image6,
        marketTitle: 'Hozzana Hostel',
        marketDetails: 'It a 100% compatible CommonMark renderer, a react-native markdown renderer done right. This is not a web-view',
        price: '70,000',
        status: 'Agent',
    },
];
