export const UPDATE_ONBOARDING_STATUS = 'UPDATE_ONBOARDING_STATUS';
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN';
export const UPDATE_USER_ACCESS_TOKEN = 'UPDATE_USER_ACCESS_TOKEN';
export const UPDATE_USER_REFRESH_TOKEN = 'UPDATE_USER_REFRESH_TOKEN';
export const UPDATE_POST_DETAILS = 'UPDATE_POST_DETAILS';
export const CLEAR_NEWS = 'CLEAR_NEWS';
export const LOGOUT_USER = 'LOGOUT_USER';
